### ISSUE TITLE
Release 0.2.5

### ISSUE THREAD

**Issue by rajatvig** [eucalyptus/magic-search#11]
Any timelines?

**Comment by dkavanagh** [comment]
Hi,
Is there something you're looking to have added?

**Comment by rajatvig** [comment]
Nothing much other than the few commits merged into master

**Comment by dkavanagh** [comment]
OK, since you're asking, I'll get those pushed to a new release! Sometimes, it's hard to know who's watching and waiting!

**Comment by dkavanagh** [comment]
0.2.5 is now available on bower.io
