### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by consigliory** [eucalyptus/magic-search#5]
this is great work. Can you do demo page?

**Comment by dkavanagh** [comment]
Actually, I could! While there is server-side filtering intended, I could mock that on the client.

**Comment by consigliory** [comment]
Awesome! Thanks!!!

**Comment by atomicleopard** [comment]
Agreed, this sounds like an awesome widget but is hard to assess and implement without a demo page (for example I didnt see how you actually supply the facets json). I'll install and give it a whirl.

**Comment by dkavanagh** [comment]
I've linked the demo page from the main repo page. Here's the URL: http://eucalyptus.github.io/magic-search
