### ISSUE TITLE
backspace and space problem

### ISSUE THREAD

**Issue by cina2012** [eucalyptus/magic-search#6]
hi.
tnx for nice and great work.
i have a problem with backspace and space:
i typed L and drop down show Location and Blades, but when i press backspace 
dropdown alrady shown Location and Blades until i press ESC.
also when i select location and i press space, last selected is deleted.

**Comment by dkavanagh** [comment]
Thanks and let me have a look. The demo is somewhat rigged up and doesn't function as cleanly as our implementation in Eucalyptus which uses XHR to fetch new data based on facets. I tried to "fudge" it all in javascript for the demo and may have missed something.

**Comment by dkavanagh** [comment]
I'm finally getting time to look at this. I think this is within the demo since I don't see this behavior in my application. I'll try tracking this down today.

**Comment by dkavanagh** [comment]
I have a patch for magic-search to fix this. I needed a $scope.$apply inside a key listener.
